# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0
version: "3.7"

networks:
  docker_mainflux-base-net:
    external: true

services:
  telegraf-stat:
    image: mainflux/telegraf:latest
    container_name: telegraf-stat
    networks:
      - docker_mainflux-base-net
    volumes:
      - ./telegraf.nats.conf:/etc/telegraf/telegraf.conf:ro
  